### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by Gabrock94** [Gabrock94/pyaesthetics#1]
- [x] Fix warning in text / image ratio when area of the image  == 0
``
/usr/local/lib/python3.5/dist-packages/prettywebsite-0.0.4-py3.5.egg/prettywebsite/spaceBasedDecomposition.py:63: RuntimeWarning: divide by zero encountered in long_scalars
  return({"textImageRatio":sum(text) / sum(image),"textArea":sum(text),"imageArea":sum(image),"nImages":len(image)})
``

**Comment by Gabrock94** [comment]
From Braun, J., Amirshahi, S. A., Denzler, J., & Redies, C. (2013). Statistical image properties of print advertisements, visual artworks and images of architecture. Frontiers in Psychology, 4, 808.:

 - [x] Add self-similarity (PHOG method)
 - [x] Add complexity (PHOG method)
 - [x] Add anisotropy (PHOG method)

**Comment by Gabrock94** [comment]
- [x] Add links to instruction on tesseract's installation

**Comment by Gabrock94** [comment]
- [x] Change face recognition algorithm to face-recognition
